export const imagesConfig = {
    backpack: "assets/images/prizes/backpack.png",
    bag_laptop: "assets/images/prizes/bag_laptop.png",
    bag: "assets/images/prizes/bag.png",
    bottle: "assets/images/prizes/bottle.png",
    certificate: "assets/images/prizes/certificate.png",
    fly: "assets/images/prizes/fly.png",
    memory_card: "assets/images/prizes/memory_card.png",
    notebook: "assets/images/prizes/notebook.png",
    pen: "assets/images/prizes/pen.png",
    pendant: "assets/images/prizes/pendant.png",
    phone_cover: "assets/images/prizes/phone_cover.png",
    powerbank: "assets/images/prizes/powerbank.png",
    signal: "assets/images/prizes/signal.png",
    towel: "assets/images/prizes/towel.png",
    SYM1_old: "assets/images/prizes/SYM1_old.png",
    SYM2_old: "assets/images/prizes/SYM2_old.png",
    SYM3_old: "assets/images/prizes/SYM3_old.png",
    SYM4_old: "assets/images/prizes/SYM4_old.png",
    SYM5_old: "assets/images/prizes/SYM5_old.png",
    SYM7_old: "assets/images/prizes/SYM7_old.png",
    SYM8_old: "assets/images/prizes/SYM8_old.png",
    SYM9_old: "assets/images/prizes/SYM9_old.png",
    SYM10_old: "assets/images/prizes/SYM10_old.png",
    SYM11_old: "assets/images/prizes/SYM11_old.png",
    SYM12_old: "assets/images/prizes/SYM12_old.png",
};